[workspace]
members = [
    "accord"
]

[workspace.package]
name = "synevi"
version = "0.1.0"
edition = "2021"
authors = ["Sebastian Beyvers <sb@pus.de>", "Jannis Hochmuth <jannis.hochmuth@cb.jlug.de>", "Lukas Brehm <lukas.brehm@cb.jlug.de>"]
repository = "https://github.com/ArunaStorage/synevi"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }