[package]
name = "consensus"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
consensus_transport = { path = "../consensus_transport" }
anyhow = {workspace = true}
bytes = "1.6.0"
chrono = "0.4.38"
diesel-ulid = "0.3.1"
tonic = {workspace = true}
tokio = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
log = "0.4.21"