[package]
name = "persistence"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = {workspace = true}
bytes = {workspace = true}
rocksdb = "0.22.0"
tokio = {workspace = true}
